from tests.test_base import TestBase
from tests.test_abstract_model import AbstractModelTest
from tests.test_addition import AdditionTest
from tests.test_scalar_weighted_addition import ScalarWeightedAdditionTest
from tests.test_vector_weighted_addition import VectorWeightedAdditionTest
from tests.test_matrix import MatrixTest
from tests.test_bilinear import BiLinearTest
from tests.test_wmask import WMaskTest
from tests.test_fulllex import FullLexTest
from tests.test_transweight import TransWeightTest
from tests.test_transweight_features import TransWeightFeaturesTest
from tests.test_transweight_matrix import TransWeightMatrixTest
from tests.test_transweight_transformations import TransWeightTransformationsTest
from tests.test_training_graph import TrainingGraphTest
from tests.test_ops import UVAffineTransformationTest, InitializationOpsTest, HashTableInitTest
from tests.test_evaluation import EvaluationTest
from tests.test_evaluation_composed import EvaluationComposedBasedTest
from tests.test_data import DataTest
